### PR TITLE
Install add-ons

### PR DESCRIPTION
**Pull request by alecpm**
This PR enables a few add-ons and sets version pins. It does some small re-organization of the buildout configs to make source configuration easier.

### CODE REVIEW

**Comment by witekdev** [comment]
@alecpm do we need to version pin some mosaic KGS? Or does Plone 5.2.4 do that?

**Review by witekdev — COMMENTED** [review]
Looks good
I was able to install jazkarta.tessarae. Is it python3 compatible or is that still something that needs to happen?

Do we need to version pin some mosaic KGS? Or does Plone 5.2.4 do that? or are the ones pinned by latest 5.2 already KGS?

**Comment by witekdev** [comment]
@alecpm did you see https://github.com/jazkarta/jazkarta.tesserae/issues/1 ?

**Comment by alecpm** [comment]
I did see that, but then promptly forgot about it. Will take a look.

Plone 5.2 includes [mosaic KGS pins](https://dist.plone.org/release/5.2-latest/versions.cfg)

**Pull request merged**
